queryParameters:
  page:
    displayName: Page number
    type: integer
    minimum: 1
    maximum: 2147483647
    description: Page number of cost-per-use results
    example: 1
    default: 1
  size:
    displayName: Size
    type: integer
    minimum: 10
    maximum: 1000
    description: Count of number of cost-per-use results
    example: 100
    default: 100
