queryParameters:
  filter[selected]:
    displayName: Selection status
    type: string
    description: Filter to narrow down results based on selection status. Possible values are all, true, false, ebsco.
    example: all
    required: false
  filter[type]:
    displayName: Content type
    type: string
    description: |
      Filter to narrow down results based on content type. Defaults to all.
      Possible values are all, aggregatedfulltext, abstractandindex, ebook, ejournal, print, unknown, streamingmedia, mixedcontent, onlinereference.
    example: ebook
    default: all
    required: false
