queryParameters:
  filter[selected]:
    displayName: Selection status
    type: string
    enum: ["all", "true", "false", "ebsco"]
    description: Filter to narrow down results based on selection status
    required: false
  filter[type]:
    displayName: Content type
    type: string
    enum: ["all", "aggregatefulltext", "abstractandindex", "ebook", "ejournal", "print", "unknown", "onlinereference"]
    description: Filter to narrow down results based on content type
    default: all
    required: false