queryParameters:
  include:
    displayName: Nested resource
    type: string
    enum: [ packages ]
    description: Name of nested resource to include
    default: packages
    example: packages
    required: false
