queryParameters:
  include:
    displayName: Related Resources
    type: string
    enum: [resources]
    description: Include related resource obects, each representing a partnering of this title with a package.  Any bogus value, like `include=deciduousTrees`, will be silently ignored.
    default: resources
    example: resources
    required: false
