queryParameters:
  sort:
    displayName: Sort options
    type: string
    description: Option by which results are sorted. Defaults to relevance if query or name if no query.
    example : |
      ["name", "relevance"]
    default: relevance
    required: false
