queryParameters:
  sort:
    displayName: Sort options
    type: string
    description: Option by which results are sorted. Possible values are <<possibleValues>>.
    default: <<defaultValue>>
    required: false
