ALTER TABLE holdings_status
ADD COLUMN IF NOT EXISTS retry_attempts_left INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_pages INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS pages_loaded INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS retry_timer_id BIGINT;
