ALTER TABLE holdings
  ALTER COLUMN id TYPE VARCHAR (50),
  DROP COLUMN IF EXISTS jsonb,
  ADD COLUMN IF NOT EXISTS credentials_id UUID NOT NULL,
  ADD COLUMN IF NOT EXISTS vendor_id VARCHAR (10),
  ADD COLUMN IF NOT EXISTS package_id VARCHAR (10),
  ADD COLUMN IF NOT EXISTS title_id VARCHAR (10),
  ADD COLUMN IF NOT EXISTS resource_type VARCHAR (20) NOT NULL,
  ADD COLUMN IF NOT EXISTS publisher_name VARCHAR (200),
  ADD COLUMN IF NOT EXISTS publication_title VARCHAR (300),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE holdings
  DROP CONSTRAINT IF EXISTS holdings_pkey,
  DROP CONSTRAINT IF EXISTS pk_holdings,
  ADD CONSTRAINT pk_holdings primary key (credentials_id, id);

ALTER TABLE holdings
  DROP CONSTRAINT IF EXISTS fk_holdings_kb_credentials,
  ADD CONSTRAINT fk_holdings_kb_credentials FOREIGN KEY (credentials_id) REFERENCES kb_credentials (id) ON DELETE CASCADE;
