ALTER TABLE titles
DROP COLUMN IF EXISTS jsonb,
ALTER COLUMN id TYPE VARCHAR (50),
ADD COLUMN IF NOT EXISTS name VARCHAR (200) NOT NULL;

CREATE INDEX IF NOT EXISTS titles_name_index ON titles (name);
