#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

types:
  assignedUserId: !include types/assignedUsers/assignedUserId.json
  assignedUserCollection: !include types/assignedUsers/assignedUserCollection.json
  assignedUserPostRequest: !include types/assignedUsers/assignedUserPostRequest.json
  assignedUserPutRequest: !include types/assignedUsers/assignedUserPutRequest.json
  jsonapiError: !include types/jsonapiError.json

/eholdings/kb-credentials/{id}/users:
  displayName: Users assigned to KB Credentials
  uriParameters:
    id:
      pattern : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
  get:
    description: Retrieve users information assigned to a specific KB credentials.
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            type: assignedUserCollection
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_get_200_response.json
      400:
        description: Bad Request
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_get_400_response.json
  post:
    description: Assign user to a specific KB credentials.
    headers:
      Content-Type:
        example: application/vnd.api+json
    body:
      application/vnd.api+json:
        description: Assign user to KB credentials
        type: assignedUserPostRequest
        example:
          strict: false
          value: !include examples/assignedUsers/assigned_users_post_request.json
    responses:
      201:
        description: Created
        body:
          application/vnd.api+json:
            description: The server has successfully fulfilled the POST request.
            type: assignedUserId
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_post_201_response.json
      400:
        description: Bad Request
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_post_400_response.json
      404:
        description: Not Found
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_post_404_response.json
      422:
        description: Unprocessable Entity
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_post_422_response.json
  /{userId}:
    displayName: Particular user assigned to KB Credentials
    uriParameters:
      userId:
        pattern : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    put:
      body:
        application/vnd.api+json:
          description: Update User Assignment to KB Credentials
          type: assignedUserPutRequest
          example:
            strict: false
            value: !include examples/assignedUsers/assigned_users_put_request.json
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_users_put_400_response.json
        404:
          description: Not Found
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_users_put_404_response.json
        422:
          description: Unprocessable Entity
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_users_put_422_response.json
    delete:
      description: Remove association between user and KB Credentials
      responses:
        204:
          description: No Content
        404:
          description: Not Found
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_users_delete_404_response.json
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_users_delete_400_response.json
