#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

types:
  assignedUser: !include types/assignedUsers/assignedUser.json
  assignedUserCollection: !include types/assignedUsers/assignedUserCollection.json
  jsonapiError: !include types/jsonapiError.json

/eholdings/kb-credentials/{id}/users:
  displayName: Users assigned to KB Credentials
  uriParameters:
    id:
      pattern : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
  get:
    description: Retrieve users information assigned to a specific KB credentials.
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            type: assignedUserCollection
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_get_200_response.json
      400:
        description: Bad Request
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/assignedUsers/assigned_users_get_400_response.json
  /{userId}:
    displayName: Assigned User by ID
    description: Instance of a assigned user by given id
    uriParameters:
      userId:
        pattern : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    get:
      description: Retrieve assigned user by id
      responses:
        200:
          description: OK
          body:
            application/vnd.api+json:
              type: assignedUser
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_user_get_200_response.json
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_user_get_400_response.json
        404:
          description: Not Found
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/assignedUsers/assigned_user_get_404_response.json
