#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

traits:
  resourceQueryParameters:
      queryParameters:
        platform:
          displayName: Type of platform
          description: |
            Include publisher, non-publisher or all platforms
            Possible values are
             - publisher
             - nonPublisher
             - all
          type: string
          required: false
        fiscalYear:
          displayName: Fiscal year
          description: Fiscal year of cost-per-use data
          type: string
          pattern: "^\\d{4}$"
          required: true

types:
  resourceCostPerUse: !include types/uc/costperuse/resourceCostPerUse.json
  jsonapiError: !include types/jsonapiError.json

/eholdings/resources/{resourceId}/costperuse:
  displayName: Cost-per-use
  uriParameters:
    resourceId:
      description: Identifier of the resource formed from Provider Id, Package Id, Title Id
      type: string
      pattern: "^\\d+-\\d+-\\d+$"
      example: 22-1887786-1440285
  get:
    description: Retrieve cost-per-use information for a particular resource
    is: [resourceQueryParameters]
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            description: Resource cost-per-use
            type: resourceCostPerUse
            example:
              strict: false
              value: !include examples/costPerUse/resource_cost_per_use_200_response.json
      400:
        description: Bad Request
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/costPerUse/resource_cost_per_use_400_response.json
      422:
        description: Unprocessable Entity
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/costPerUse/resource_cost_per_use_422_response.json
