#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

traits:
  resourceQueryParameters:
      queryParameters:
        platform:
          displayName: Type of platform
          description: |
            Include publisher, non-publisher or all platforms
            Possible values are
             - publisher
             - nonPublisher
             - all
          type: string
          required: false
        fiscalYear:
          displayName: Fiscal year
          description: Fiscal year of cost-per-use data
          type: integer
          example: 2019
          required: true

types:
  platformType: !include types/uc/platformType.json
  resourceCostPerUse: !include types/uc/costperuse/resourceCostPerUse.json
  uCSettingsPatchRequest: !include types/uc/uCSettingsPatchRequest.json
  jsonapiError: !include types/jsonapiError.json

/eholdings/resources/{resourceId}/costperuse:
  displayName: Cost-per-use
  uriParameters:
    resourceId:
      description: Identifier of the resource formed from Provider Id, Package Id, Title Id (see example)
      type: string
      pattern: "^\\d+-\\d+-\\d+$"
      example: 22-1887786-1440285
  get:
    description: Retrieve cost-per-use information for a particular resource
    is: [resourceQueryParameters]
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            description: Usage Consolidation settings
            type: resourceCostPerUse
            example:
              strict: false
              value: !include examples/uc/uc_settings_get_200_response.json
      404:
        description: Not Found
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/uc/uc_settings_get_404_response.json
