#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

types:
  configuration: !include types/configuration/configuration.json
  configurationPutRequest: !include types/configuration/configurationPutRequest.json
  jsonapiError: !include types/jsonapiError.json
  configurationStatus: !include types/status/status.json
  holdingsLoadingStatus: !include types/loadHoldings/loadingHoldingsStatus.json

/eholdings/configuration:
  displayName: Configuration
  description: Setup KB Configuration.
  get:
    description: Details of KB configuration currently being used.
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            description: Details of KB configuration currently being used.
            type: configuration
            example:
              strict: false
              value: !include examples/configuration/kb_configuration_get_200_response.json
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  put:
    description: |
      Update the currently set KB configuration.
    headers:
      Content-Type:
        example: application/vnd.api+json
    body:
      application/vnd.api+json:
        type: configurationPutRequest
        example: !include examples/configuration/kb_configuration_put_request.json
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            type: configuration
            example:
              strict: false
              value: !include examples/configuration/kb_configuration_put_200_response.json
      422:
        description: Unprocessable Entity
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/configuration/kb_configuration_put_422_response.json
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
/eholdings/status:
  displayName: Status
  description: Gives status of currently set KB configuration.
  get:
    description: Gives status of currently set KB configuration.
    responses:
      200:
        body:
          application/vnd.api+json:
            description: Status of currently set KB configuration.
            type: configurationStatus
            example:
              strict: false
              value: !include examples/status/status_get_200_response.json
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
/eholdings/cache:
  displayName: Cache
  delete:
    description: |
      Invalidate configuration cache for tenant
    responses:
      204:
        description: No Content

/loadHoldings:
  displayName: Run load holdings job
  post:
    description: Run load holdings job.
    headers:
      Content-Type:
        example: application/json
    responses:
      204:
        description: No Content
      409:
        description: "Process of loading holdings is already running"
        body:
          text/plain:
            example: "Process of loading holdings is already running"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /status:
    displayName: Get current status of load holdings job.
    get:
      description: Get current status of load holdings job.
      headers:
        Content-Type:
          example: application/json
      responses:
        200:
          body:
            application/json:
              description: Get current status of load holdings job.
              type: holdingsLoadingStatus
              example:
                strict: false
                value: !include examples/loadHoldings/loading_completed_200_response.json
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
