#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

types:
  kbCredentials: !include types/kbCredentials/kbCredentials.json
  kbCredentialsCollection: !include types/kbCredentials/kbCredentialsCollection.json
  kbCredentialsPutRequest: !include types/kbCredentials/kbCredentialsPutRequest.json
  kbCredentialsPostRequest: !include types/kbCredentials/kbCredentialsPostRequest.json
  assignedUserCollection: !include types/assignedUsers/assignedUserCollection.json
  jsonapiError: !include types/jsonapiError.json

/eholdings/kb-credentials:
  displayName: KB Credetntials
  get:
    description: Get a collection of KB credentials.
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            description: Collection of KB credentials available.
            type: kbCredentialsCollection
            example:
              strict: false
              value: !include examples/kbCredentials/kb_credentials_collection_get_200_response.json
      401:
        description: "Not authorized to perform requested action"
        body:
          text/plain:
            example: "Invalid token"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  post:
    description: Create KB credentials
    headers:
      Content-Type:
        example: application/vnd.api+json
    body:
      application/vnd.api+json:
        description: Create KB credentials
        type: kbCredentialsPostRequest
        example:
          strict: false
          value: !include examples/kbCredentials/kb_credentials_post_request.json
    responses:
      201:
        description: Created
        body:
          application/vnd.api+json:
            description: The server has successfully fulfilled the POST request.
            type: kbCredentials
            example:
              strict: false
              value: !include examples/kbCredentials/kb_credentials_post_201_response.json
      400:
        description: Bad Request
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/kbCredentials/kb_credentials_post_400_response.json
      401:
        description: "Not authorized to perform requested action"
        body:
          text/plain:
            example: "Invalid token"
      422:
        description: Unprocessable Entity
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/kbCredentials/kb_credentials_post_422_response.json
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{id}:
    displayName: KB Credentials by ID
    description: Instance of a KB credentials by given id
    uriParameters:
      id:
        pattern : "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    get:
      description: Get a specific KB credentials by id.
      responses:
        200:
          description: OK
          body:
            application/vnd.api+json:
              type: kbCredentials
              example:
                strict: false
                value: !include examples/kbCredentials/kb_credentials_get_200_response.json
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
              example: "Invalid token"
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/kbCredentials/kb_credentials_get_400_response.json
        404:
          description: Not Found
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/kbCredentials/kb_credentials_get_404_response.json
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
    put:
      description: Update KB credentials
      headers:
        Content-Type:
          example: application/vnd.api+json
      body:
        application/vnd.api+json:
          description: Create KB credentials
          type: kbCredentialsPutRequest
          example:
            strict: false
            value: !include examples/kbCredentials/kb_credentials_put_request.json
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/kbCredentials/kb_credentials_put_400_response.json
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
              example: "Invalid token"
        404:
          description: Unprocessable Entity
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/kbCredentials/kb_credentials_put_404_response.json
        422:
          description: Unprocessable Entity
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/kbCredentials/kb_credentials_put_422_response.json
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
    delete:
      description: Delete KB Credentials
      responses:
        204:
          description: No Content
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
              example: "Invalid token"
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/kbCredentials/kb_credentials_delete_400_response.json
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
