#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

types:
  providerCollection: !include types/providers/providerCollection.json
  providerPutData: !include types/providers/providerPutData.json
  
traits:
  queriable: !include traits/queriable.raml
  filterable: !include traits/filterable.raml

/eholdings/providers:
  displayName: Providers
  description: Collection of available providers in eholdings.
  get:
    description: Get a list of providers based on the search query.
    is: [queriable]
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            description: List of providers matching the provider name and the total number of providers found.
            type: providerCollection
            example:
              strict: false
              value: !include examples/providers/providers_get_200_response.json
 