#%RAML 1.0
title: mod-kb-ebsco-java
baseUri: https://github.com/folio-org/mod-kb-ebsco-java
protocols: [ HTTPS ]
version: v1
mediaType: "application/vnd.api+json"

documentation:
  - title: mod-kb-ebsco-java
    content: Implements the eholdings interface using EBSCO KB as backend.

types:
  resourcePostRequest: !include types/resources/resourcePostRequest.json
  resource: !include types/resources/resource.json
  jsonapiError: !include types/jsonapiError.json
  resourcePutRequest: !include types/resources/resourcePutRequest.json
  resourceTagsPutRequest: !include types/resources/resourceTagsPutRequest.json
  resourceTags: !include types/resources/resourceTags.json

/eholdings/resources:
  displayName: Resources
  post:
    description: Create a relation between an existing custom package and an existing custom/managed title.
    headers:
      Content-Type:
        example: application/vnd.api+json
    body:
      application/vnd.api+json:
        description: The server has successfully fulfilled the POST request.
        type: resourcePostRequest
        example:
          strict: false
          value: !include examples/resources/resources_post_request.json
    responses:
      200:
        description: OK
        body:
          application/vnd.api+json:
            description: The server has successfully fulfilled the POST request.
            type: resource
            example:
              strict: false
              value: !include examples/resources/resources_post_200_response.json
      400:
        description: Bad Request
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/resources/resources_post_400_response.json
      404:
        description: Not Found
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/resources/resources_post_404_response.json
      422:
        description: Unprocessable Entity
        body:
          application/vnd.api+json:
            type: jsonapiError
            example:
              strict: false
              value: !include examples/resources/resources_post_422_response.json
  /{resourceId}:
    displayName: Get resource by resourceId
    description: Instance of a resource given resourceId
    uriParameters:
      resourceId:
        description: Identifier of the resource formed from Provider Id, Package Id, Title Id (see example)
        type: string
        example: 22-1887786-1440285
    get:
      description: |
        Retrieve a specific resource given resourceId.
        Note that a resource is a managed/custom title associated with a managed/custom package.
        resourceId is providerId-packageId-titleId
      queryParameters:
        include:
          displayName: Nested provider, package or title
          type: string
          description: |
            Include provider, package or title in response
            Possible values are
             - provider
             - package
             - title
          example: provider
          required: false
      responses:
        200:
          description: OK
          body:
            application/vnd.api+json:
              description: Resource details from KB for a given resource Id
              type: resource
              example:
               strict: false
               value: !include examples/resources/resources_resourceId_get_200_response.json
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_get_400_response.json
        404:
          description: Not Found
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_get_404_response.json
    put:
      description: |
        Update a managed or custom resource using resourceId
        Note that resourceId is providerId-packageId-titleId
      headers:
        Content-Type:
          example: application/vnd.api+json
      body:
        application/vnd.api+json:
          type: resourcePutRequest
          example:
            strict: false
            value: !include examples/resources/resources_put_request.json
      responses:
        200:
          description: OK
          body:
            application/vnd.api+json:
              description: The server has successfully fulfilled the PUT request.
              type: resource
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_put_200_response.json
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_put_400_response.json
        404:
          description: Not Found
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_put_404_response.json
        422:
          description: Unprocessable Entity
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_put_422_response.json
    delete:
      description: |
        Delete the association between a custom/managed title and a custom package using resourceId.
        Note that resourceId is providerId-packageId-titleId
        If the title is custom and is not associated with any other package, then the title will be deleted from the knowledge base.
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_delete_400_response.json
        404:
          description: Not Found
          body:
            application/vnd.api+json:
              type: jsonapiError
              example:
                strict: false
                value: !include examples/resources/resources_resourceId_delete_404_response.json
    /tags:
      put:
        description: Update tags assigned to resource
        headers:
          Content-Type:
            example: application/vnd.api+json
        body:
          application/vnd.api+json:
            type: resourceTagsPutRequest
            example:
              strict: false
              value: !include examples/resources/resource_tags_put_request.json
        responses:
          200:
            description: OK
            body:
              application/vnd.api+json:
                description: Updated list of tags
                type: resourceTags
                example:
                  strict: false
                  value: !include examples/resources/resource_tags_put_200_response.json
          422:
             description: Unprocessable Entity
             body:
              application/vnd.api+json:
                type: jsonapiError
                example:
                  strict: false
                  value: !include examples/resources/resource_tags_put_422_response.json
